# Kubernetes Secrets YAML with exposed credentials
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: production
type: Opaque
data:
  # Base64 encoded secrets (but still vulnerable when decoded)
  database-url: cG9zdGdyZXNxbDovL2FkbWluOlN1cGVyU2VjcmV0UGFzc3dvcmQxMjMhQGxvY2FsaG9zdDo1NDMyL3VzZXJkYg==
  api-key: c2tfbGl2ZV9mYWtlMTIzeHl6Nzg5X3NlY3JldF9rZXk=
  jwt-secret: aGFyZGNvZGVkLWp3dC1zZWNyZXQta2V5LTEyMzQ1
stringData:
  # Plain text secrets (highly vulnerable)
  admin-password: "AdminPassword123!"
  stripe-key: "sk_live_fake_51JxMGaGqf7sKr7TZMtZtYDhYzVQiLZuRKt3eF3lJ8nZKaJ4jK2aZ9sP8tL"
  aws-access-key: "AKIAIOSFODNN7EXAMPLE"
  aws-secret-key: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
  google-api-key: "AIzaSyDxyz123456789abcdefghijklmnopqrstuvw"
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: production
data:
  config.properties: |
    # Application configuration with embedded secrets
    database.host=prod-db.company.com
    database.username=dbadmin
    database.password=ProductionDBPassword123!
    
    # API endpoints with credentials
    external.api.url=https://api.partner.com/v1
    external.api.key=partner-api-key-abcd1234efgh5678
    
    # Admin access
    admin.email=admin@company.com
    admin.default.password=admin123
    
    # Third-party integrations
    slack.webhook=https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX
    discord.bot.token=ODc2NTQzMjEwOTg3NjU0MzIx.YR7G_w.abcdefghijklmnopqrstuvwxyz123456
    
  user-data.json: |
    {
      "test_users": [
        {
          "id": 1,
          "email": "test.user@company.com",
          "ssn": "123-45-6789",
          "credit_card": "4532-1234-5678-9012",
          "medical_conditions": ["diabetes", "hypertension"]
        },
        {
          "id": 2,
          "email": "jane.doe@company.com", 
          "ssn": "987-65-4321",
          "credit_card": "5555-4444-3333-2222",
          "salary": 85000,
          "emergency_contact": "555-987-6543"
        }
      ]
    }